language: cpp
env:
  global:
    - secure: "fHPxJHwBxb7yTxmGm9pKLbZh0r3Xd7PAfoiiOMPOkFYbsQUJQ+Xbj7eDdpJYN9aTFmsEE6WiidUet6TvWUlC2c2Wr3vb16D0ANgnFGap2BXWrpsJQpn7m9jIs86z7jzIbZoc3Xf24ohpwba3XivI0j33F0RLRbVcsRUo/Km46kuejBg9Qef7+oFIWQYCYgbWoGmKJv030RlUgFgwnIR1vD7K09A3zm6rYJTCvP9swr3XBO8dzWuL/+vfX+xHxkNPFCzq0ETVf2VSD8giIeAmKEQoiTWzieeGZvdnknY2kWVySgAkw8wVC8+N4N0MhvagzrtWzGsjnQQCWlc6QL4naOTb36z7wAg0iFtGvuhEN2OJhtGDW9vyhiVn+sAsu0fq7MH0idG1FrWc3lL5ogqdqbCpdbekCGSphhtRxqkD/iDfEiY4QaO/9OMlaTxUUQsgGIXAB+UZFlBO0TVYu+TkhYr2nk2cmhvGhz5tqsWpiks0oKbySYxuLcDMO20FzEKqQsroCLo70LKOW5CkFBDUCpp+WXgaFnxbyxw6G4Zl+EVZpBXPb35+oRjVv0Gs2ubGjlmEZzfzVZkjBqAjJ7c5eHEIUizyPAgxQVQaj+cV1s5aHpWPOLGvTLYJkEvRVSG0oSDdiH1wtVHuf/7rTZsupxHGVvbohZGHxiIZHfOwYZc="
branches:
    only:
        - master
matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
          env: CUDA=ON
cache:
    directories:
        - $HOME/.local
before_install: |
    if [ "$CUDA" = ON ]; then
      . scripts/install-cuda-ubuntu1604.sh
    fi
    if [ "$TRAVIS_OS_NAME" = linux ]; then
      scripts/install_cmake.sh
      sudo pip install --upgrade requests pyopenssl
    elif [ "$TRAVIS_OS_NAME" == "osx" ]; then
      sudo pip install requests
    fi
script:
    - cmake -DHUNTER_JOBS_NUMBER=4 -DETHASHCUDA=$CUDA -DETHASHCL=ON -DAPICORE=ON -H. -Bbuild
    - cmake --build build -- -j4
    - build/ethminer/ethminer --list-devices -G
    - build/ethminer/ethminer --list-devices -U
    - if [ "$TRAVIS_OS_NAME" = linux ]; then ldd -v build/ethminer/ethminer; fi
    - cmake --build build --target package
